BEGIN TRAN

INSERT INTO AppMaritalStatusTypes (Id, MaritalStatusDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 1, 'Libero', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppMaritalStatusTypes (Id, MaritalStatusDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 2, 'Nubile', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppMaritalStatusTypes (Id, MaritalStatusDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 3, 'Celibe', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppMaritalStatusTypes (Id, MaritalStatusDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 4, 'Coniugato', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppMaritalStatusTypes (Id, MaritalStatusDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 5, 'Vedovo', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppMaritalStatusTypes (Id, MaritalStatusDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 6, 'Separato', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppMaritalStatusTypes (Id, MaritalStatusDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 7, 'Divorziato', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppMaritalStatusTypes (Id, MaritalStatusDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 8, 'Convivente', NULL, NULL, GETDATE(), GETDATE()

INSERT INTO AppFamilyType (Id, FamilyTypeDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 1, 'Single senza figli', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppFamilyType (Id, FamilyTypeDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 2, 'Single con figli', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppFamilyType (Id, FamilyTypeDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 3, 'Coppia senza figli', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppFamilyType (Id, FamilyTypeDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 4, 'Coppia con 1 figlio', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppFamilyType (Id, FamilyTypeDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 5, 'Coppia con 2 figli', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppFamilyType (Id, FamilyTypeDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 6, 'Coppia con 3 o più figli', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppFamilyType (Id, FamilyTypeDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 7, 'Nucleo con più familiari a carico', NULL, NULL, GETDATE(), GETDATE()

INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 1, 'NESSUNA ATTIVITA’ DICHIARATA', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 2, 'ABBATTITORI DI PIANTE, ADDETTI ALLA POTATURA', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 3, 'AGENTI DI CAMBIO E DI BORSA. AGENTI IMMOBILIARI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 4, 'AGENTI DI COMMERCIO ', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 5, 'AGENTI DI ASSICURAZIONE ', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 6, 'Albergatori senza prestazioni manuali', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 7, 'Albergatori con prestazioni manuali', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 8, 'ALLENATORI SPORTIVI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 9, 'Allevatori di animali che non prestano opera manuale', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 10, 'Allevatori di altri animali o che comunque prestano lavoro manuale ', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 11, 'Amministratori di beni propri o altrui', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 12, 'Analisti chimici', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 13, 'Antennisti, riparatori (con installazione di antenne radio-TV) ', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 14, 'Antiquari senza restauro', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 15, 'Architetti occupati prevalentemente in ufficio', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 16, 'Architetti occupati prevalentemente all''esterno ma senza accesso ai cantieri', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 17, 'Architetti occupati prevalentemente all''esterno con accesso ai cantieri', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 18, 'Autisti di autovetture in servizio pubblico o privato, taxi, autoambulanza, autofunebri', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 19, 'Autisti di autobus pubblici e da turismo, autocarri, motocarri, autotreni, autoarticolati senza carico e scarico', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 20, 'Autisti di autocarri, motocarri, autotreni, autoarticolati con carico e scarico', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 21, 'Autorimesse: esercenti che non lavorano manualmente', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 22, 'Autorimesse: addetti a lavori di riparazione, manutenzione, lavaggio ecc.', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 23, 'Avvocati e procuratori legali', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 24, 'BARBIERI, PARRUCCHIERI DA DONNA', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 25, 'BENESTANTI SENZA PARTICOLARI OCCUPAZIONI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 26, 'BIDELLI, CUSTODI DI MUSEI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 27, 'Calciatori di serie A-B-C', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 28, 'Calciatori di altre serie o divisioni', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 29, 'CALLISTI, MANICURE, PEDICURE, ESTETISTI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 30, 'Calzolai', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 31, 'Camerieri', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 32, 'Carpentieri in legno o ferro', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 33, 'Autoriparatori (carrozzieri o meccanici), gommisti, vulcanizzatori', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 34, 'Casalinghe', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 35, 'Casari', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 36, 'Cave a giorno con o senza uso di mine: proprietari o addetti che non lavorano manualmente', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 37, 'Cave a giorno senza uso di mine: proprietari o addetti che lavorano manualmente', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 38, 'Cave a giorno con uso di mine: proprietari o addetti che lavorano manualmente', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 39, 'Ciclisti: corridori professionisti', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 40, 'Ciclisti: corridori dilettanti', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 41, 'Clero (appartenenti al)', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 42, 'Commercialisti, Consulenti del lavoro', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 43, 'Concessionari auto-motoveicoli (solo vendita)', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 44, 'Corniciai', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 45, 'Cuochi', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 46, 'Disegnatori occupati solo in ufficio', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 47, 'DISTRIBUTORI AUTOMATICI DI CARBURANTE (GESTORI DI) SENZA OPERAZIONI MANUTENZIONE, LAVAGGIO E SIMILI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 48, 'DISTRIBUTORI AUTOMATICI DI CARBURANTE (GESTORI DI) CON OPERAZIONI DI MANUTENZIONE, LAVAGGIO E SIMILI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 49, 'Domestici, collaboratori familliari ', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 50, 'Elettrauto', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 51, 'Elettricisti che lavorano solo all''interno di edifici ed a contatto con correnti a bassa tensione (< 600 V. corrente continua, e < 400 V. corrente alternata)', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 52, 'Elettricisti che lavorano anche all''esterno di edifici ed a contatto anche con correnti ad alta tensione', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 53, 'Enologi ed enotecnici', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 54, 'Fabbri solo a terra', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 55, 'Fabbri anche su impalcature e ponti', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 56, 'Facchini (portabagagli di piccoli colli)', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 57, 'Facchini addetti al carico e scarico di merci in genere (portuali, doganali, ecc.)', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 58, 'Falegnami', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 59, 'Fantini', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 60, 'Floricoltori', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 61, 'Fotografi solo in studio', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 62, 'Fotografi anche all''esterno', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 63, 'GEOLOGI OCCUPATI ANCHE ALL’ESTERNO', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 64, 'Geometri occupati solo in ufficio', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 65, 'Geometri occupati anche all''esterno ma senza accesso ai cantieri', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 66, 'Geometri che accedono anche ai cantieri', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 67, 'GIARDINIERI - VIVAISTI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 68, 'Giornalisti (cronisti, corrispondenti), scrittori', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 69, 'GUARDIACACCIA, GUARDIAPESCA, GUARDIE CAMPESTRI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 70, 'Idraulici solo all''interno di edifici o a terra', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 71, 'IMBIANCHINI SOLO ALL’INTERNO DI EDIFICI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 72, 'IMBIANCHINI  ANCHE ALL’ESTERNO DI EDIFICI E CON USO DI SCALE, IMPALCATURE E PONTI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 73, 'Imprenditori in genere che non lavorano manualmente', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 74, 'Imprenditori edili che possono prendere parte ai lavori', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 75, 'Imprenditori in genere che possono prendere parte ai lavori', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 76, 'Infermieri diplomati, paramedici, ', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 77, 'Ingegneri occupati solo in ufficio', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 78, 'Ingegneri occupati anche all''esterno ma senza accesso ai cantieri', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 79, 'Ingegneri che accedono anche ai cantieri', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 80, 'Insegnanti di alpinismo, guide alpine', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 81, 'INSEGNANTI DI EQUITAZIONE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 82, 'INSEGNANTI DI JUDO, KARATE OD ALTRI SIMILARI, INSEGNANTI DI ATLETICA PESANTE ED ARTI MARZIALI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 83, 'Insegnanti di educazione fisica, sci, basket, tennis, scherma, ballo, atletica leggera, nuoto', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 84, 'Insegnanti di materie non sperimentali e non di pratica professionale', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 85, 'INSEGNANTI DI MATERIE SPERIMENTALI ANCHE IN LABORATORIO O DI PRATICA PROFESSIONALE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 86, 'Ispettori di assicurazione, scolastici ed in genere', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 87, 'Istruttori di teoria di scuola guida', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 88, 'Istruttori di pratica (guida) di scuola guida', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 89, 'Lattonieri anche su impalcature e ponti, Idraulici anche all''esterno', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 90, 'Litografi e tipografi', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 91, 'Magistrati', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 92, 'Magliaie', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 93, 'Massaggiatori, fisioterapisti', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 94, 'Materassai', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 95, 'Mediatori in genere (escluso bestiame)', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 96, 'Mediatori di bestiame', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 97, 'Medici (per i radiologi sono esclusi gli effetti sia interni che esterni delle emanazioni radioattive), Biologi e Psicologi', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 98, 'Mobilieri: fabbricazione mobili in ferro', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 99, 'Mobilieri: fabbricazione mobili in legno', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 100, 'Esercizi Commerciali :Abiti, confezioni, mercerie, pellicce, tessuti', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 101, 'Esercizi Commerciali :Articoli in pelle, calzature', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 102, 'Esercizi Commerciali :Giocattoli, articoli sportivi', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 103, 'Esercizi Commerciali :Cartolerie, librerie, edicole', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 104, 'Esercizi Commerciali :Articoli ed apparecchi fotografici e di ottica, dischi e musica, strumenti musicali', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 105, 'Esercizi Commerciali : Farmacie e Farmacisti', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 106, 'Esercizi Commerciali : Oreficerie, orologerie, gioiellerie', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 107, 'Esercizi Commerciali :Rivendita pane, latterie, pasticcerie e gelaterie senza produzione propria', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 108, 'Esercizi Commerciali : Tabaccherie, profumerie, drogherie, vini e liquori', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 109, 'Esercizi Commerciali : Frutta e verdura, fiori e piante', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 110, 'Esercizi Commerciali : Casalinghi, armi', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 111, 'Esercizi Commerciali : Ferramenta, colori e vernici, accessori per autoveicoli', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 112, 'Esercizi Commerciali :Elettrodomestici, radio-TV, mobili, articoli igienico-sanitari: con o senza installazione ma esclusa la posa e riparazione di antenne', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 113, 'Esercizi Commerciali : Panetterie, pasticcerie, gelaterie: per tutti compresa produzione propria', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 114, 'Esercizi Commerciali: Salumerie, rosticcerie, macellerie, pescherie', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 115, 'Esercizi Commerciali : Bar, caffè, bottiglierie, proprietari/ addetti a birrerie, enoteche, paninoteche', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 116, 'Esercizi Commerciali : Ristoranti, trattorie, pizzerie', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 117, 'Notai', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 118, 'Odontotecnici', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 119, 'Ortopedici (fabbricanti di apparecchi)', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 120, 'Ostetriche', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 121, 'Periti liberi professionisti occupati anche all''esterno', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 122, 'Pescatori (pesca marittima costiera e d''acqua dolce)', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 123, 'Riparatori elettrodomestici, computer, radio tv (esclusa posa e riparazione di antenne)', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 124, 'Sarti', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 125, 'Speleologi', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 126, 'Studenti  di scuola  non professionale', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 127, 'Tappezzieri', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 128, 'Veterinari', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 129, 'Vetrai', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 130, 'Vetrinisti', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 131, 'Vigili del fuoco', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 132, 'Vigili urbani', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 133, 'Addetti in imprese di pulizia con uso di impalcature esterne', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 134, 'Addetti in imprese di pulizia senza uso di impalcature esterne', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 135, 'Addetti in lavanderia, pulisecco, tintorie e stirerie', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 136, 'Agronomi', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 137, 'Artisti di varietà, attori, musicisti, cantanti, agenti teatrali, ballerini (esclusi acrobati e circensi)', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 138, 'Assistenti sociali', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 139, 'Attrezzisti, macchinisti (settore spettacolo)', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 140, 'Bambini (0-5 anni)', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 141, 'Certificatori di bilancio e revisori dei conti', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 142, 'Conciai, Pellettieri, Pelliciai', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 143, 'Custodi/portieri di stabili, alberghi, musei e simili, uscieri', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 144, 'Demolitori di autoveicoli', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 145, 'ESERCITO MM AVIA CC(FF.AA.) PS Gdf con mansi. amm', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 146, 'ESERCITO MM AVIA CC(FF.AA.) PS Gdf con mansi. oper', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 147, 'Medici  tirocinanti, borsisti', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 148, 'Guide turistiche', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 149, 'Indossatori e modelli', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 150, 'Bagnini', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 151, 'Marinai - con o senza uso di macchine', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 152, 'Palombari/sommozzatori', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 153, 'PENSIONATI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 154, 'Personale del circo, giostre e simili', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 155, 'Saldatori', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 156, 'Scultori/Intagliatori', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 157, 'Sportivi professionisti ', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 158, 'Studenti di scuola professionale', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 159, 'Topografi', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 160, 'Tornitori', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 161, 'AGRICOLTORI, (PROPRIETARI, AFFITUARI, ECC) CHE NON PRENDONO PARTE AI LAVORI MANUALI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 162, 'AGRICOLTORI CHE LAVORANO MANUALMENTE CON USO DI MACCHINE A MOTORE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 163, 'AGRICOLTORI CHE LAVORANO MANUALMENTE SENZA USO DI MACCHINE A MOTORE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 164, 'Allevatori di animali che prestano lavoro manuale ', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 165, 'COMMESSI VIAGGIATORI SENZA TRASPORTO E CONSEGNA MERCE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 166, 'COMMESSI VIAGGIATORI CON TRASPORTO E CONSEGNA MERCE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 167, 'DIRIGENTI OCCUPATI SOLO IN UFFICIO O ANCHE ALL''ESTERNO ESCLUSO ACCESSI A OFFICINE, CANTIERI, PONTEGGI, IMPALCATURE ECC.', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 168, 'Dirigenti occupati anche all''esterno con accesso a officine, cantieri, ponteggi, impalcature ecc.', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 169, 'Disegnatori con accesso ai cantieri', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 170, 'GEOLOGI OCCUPATI SOLO IN UFFICIO', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 171, 'GEOLOGI OCCUPATI ANCHE ALL''ESTERNO', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 172, 'Guardie notturne, giurate, guardie armate, portavalori, investigatori privati, guardie del corpo, guardie forestali', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 173, 'IMPIEGATI OCCUPATI SOLO IN UFFICIO O ANCHE ALL''ESTERNO ESCLUSO ACCESSI A OFFICINE, CANTIERI, PONTEGGI, IMPALCATURE ECC.', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 174, 'Impiegati occupati anche all''esterno con accesso a officine, cantieri, ponteggi, impalcature ecc.', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 175, 'Marmisti solo a terra', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 176, 'Marmisti anche su impalcature e ponti', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 177, 'Meccanici (DIPENDENTI) - Diversi da AUTORIPARATORI  addetti a lavori di riparazione, manutenzione, lavaggio ecc. di veicoli', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 178, 'OPERAI E LAVORATORI DIPENDENTI CON USO DI MACCHINE E ACCESSO AD OFFICINE, CANTIERI PONTEGGI ED IMPALCATURE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 179, 'MURATORI, PIASTRELLISTI, PAVIMENTATORI, PALCHETTISTI SOLO A TERRA', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 180, 'Muratori, Piastrellisti, Pavimentatori, Palchettisti anche su impalcature e ponti', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 181, 'Restauratori ed antiquari con restauro con uso di impalcature (compresi mobili)', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 182, 'Restauratori ed antiquari con restauro senza uso di impalcature (esclusi mobili)', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 183, 'STUDENTI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 184, 'ABBATTITORI DI PIANTE,ADDETTI ALLA POTATURA', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 185, 'BARBIERI, PARRUCCHIERI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 186, 'Bidelli, Custodi di musei', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 187, 'DISTRIBUTORI AUTOMATICI DI CARBURANTE (GESTORI DI) SENZA OPERAZIONI MANUTENZIONE, LAVAGGIO E SIMILI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 188, 'DISTRIBUTORI AUTOMATICI DI CARBURANTE (GESTORI DI) CON OPERAZIONI DI MANUTENZIONE, LAVAGGIO E SIMILI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 189, 'ALLENATORI SPORTIVI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 190, 'Insegnanti di equitazione', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 191, 'Callisti, manicure, pedicure, estetisti', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 192, 'Guardiacaccia, guardiapesca, guardie campestri ', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 193, 'Insegnanti di judo, karatè , od altri similari, insegnanti di atletica pesante ed arti marziali', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 194, 'AGENTI / BROKER IN FORMA INDIVIDUALE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 195, 'AGENTI DI CAMBIO', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 196, 'AGENTI IMMOBILIARI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 197, 'AGRONOMI E FORESTALI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 198, 'AGROTECNICI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 199, 'AMMINISTRATORI DI CONDOMINIO', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 200, 'ARCHITETTI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 201, 'ASSISTENTI SOCIALI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 202, 'ATTIVITA' PROFESSIONALI RELATIVE ALL'INFORMATICA', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 203, 'ATTUARI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 204, 'AVVOCATI E PROCURATORI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 205, 'COMMERCIALISTI ED ESPERTI CONTABILI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 206, 'CONSULENTI DEL LAVORO', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 207, 'CONSULENTI ED INTERMEDIARI FINANZIARI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 208, 'CONSULENTI IN PROPRIETA'' INDUSTRIALE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 209, 'GEOLOGI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 210, 'GEOMETRI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 211, 'GIORNALISTI E PUBBLICISTI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 212, 'GUIDE ALPINE ', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 213, 'GUIDE TURISTICHE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 214, 'INGEGNERI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 215, 'INTERMEDIARI ASSICURATIVI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 216, 'MAESTRI DI SCI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 217, 'NOTAI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 218, 'PERITI AGRARI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 219, 'PERITI INDUSTRIALI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 220, 'RICERCHE DI MERCATO E SONDAGGI DI OPINIONE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 221, 'SERVIZI DI INGEGNERIA INTEGRATA', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 222, 'SERVIZI LINGUISTICI ED INTERPRETI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 223, 'SPEDIZIONIERI DOGANALI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 224, 'TECNOLOGI ALIMENTARI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 225, 'ALTRO PROFESSIONISTA', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 226, 'AGENZIA - BROKER IN FORMA SOCIETARIA', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 227, 'AMMINISTRATORI DI CONDOMINIO', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 228, 'ATTUARI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 229, 'CONSULENTI DEL LAVORO', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 230, 'CONSULENTI ED INTERMEDIARI FINANZIARI NULL', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 231, 'CONSULENTI IN PROPRIETA'' INDUSTRIALE  NULL', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 232, 'GEOLOGI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 233, 'PERITI AGRARI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 234, 'PERITI INDUSTRIALI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 235, 'RICERCHE DI MERCATO E SONDAGGI DI OPINIONE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 236, 'SERVIZI DI INGEGNERIA INTEGRATA', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 237, 'SERVIZI IMMOBILIARI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 238, 'SERVIZI INFORMATICI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 239, 'SERVIZI LINGUISTICI ED INTERPRETI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 240, 'SOCIETA'' DI INGEGNERIA', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 241, 'STUDIO ASSOCIATO / SOCIETA'' MULTIDISCIPLINARE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 242, 'SOCIETA'' PAGHE E CONTRIBUTI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 243, 'STUDIO COMMERCIALISTI ', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 244, 'STUDIO DI ARCHITETTURA', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 245, 'STUDIO LEGALE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 246, 'STUDIO NOTARILE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 247, 'STUDIO TECNICO GEOMETRI', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 248, 'ALTRA TIPOLOGIA STUDIO PROFESSIONALE', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 249, 'DIPENDENTE PUBBLICO', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 250, 'Manager', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 251, 'Occupato', 0, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 252, 'Agente immobiliare', 1, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 253, 'Agente di viaggio', 1, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 254, 'Amministratore condominiale', 1, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 255, 'Area sanitaria', 1, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 256, 'Avvocati', 1, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 257, 'Commercialisti', 1, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 258, 'Consulenti del lavoro', 1, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 259, 'Dottori agronomi forestali e periti agrari', 1, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 260, 'Geologo', 1, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 261, 'Ingegnere, architetto, geometra e periti edili', 1, NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppProfessionType(Id, ProfessionTypeDescription, IsFreelancer) SELECT 262, 'Periti industriali', 1, NULL, NULL, GETDATE(), GETDATE()

INSERT INTO AppIncomeType (Id, IncomeTypeDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 1, 'Dipendente', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppIncomeType (Id, IncomeTypeDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 2, 'Autonomo', NULL, NULL, GETDATE(), GETDATE()
INSERT INTO AppIncomeType (Id, IncomeTypeDescription, CreatedBy, UpdatedBy, UpdatedDate, CreatedDate) SELECT 3, 'Professionista', NULL, NULL, GETDATE(), GETDATE()

ROLLBACK TRAN