﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using Microsoft.ML;

namespace MachineLearningModel
{
    public partial class MLClassifierCustomerFeature
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"Gender", @"Gender"),new InputOutputColumnPair(@"MaritalStatus", @"MaritalStatus"),new InputOutputColumnPair(@"IsSingle", @"IsSingle"),new InputOutputColumnPair(@"IsDependentSpouse", @"IsDependentSpouse"),new InputOutputColumnPair(@"IsFreelancer", @"IsFreelancer")}, outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"CustomerId", @"CustomerId"),new InputOutputColumnPair(@"ChildrenNumbers", @"ChildrenNumbers"),new InputOutputColumnPair(@"DependentChildrenNumber", @"DependentChildrenNumber")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"BirthMonth",outputColumnName:@"BirthMonth"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"YearBirth",outputColumnName:@"YearBirth"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"ProfessionType",outputColumnName:@"ProfessionType"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"IncomeClassType",outputColumnName:@"IncomeClassType"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"IncomeType",outputColumnName:@"IncomeType"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Country",outputColumnName:@"Country"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Region",outputColumnName:@"Region"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"InsurancePolicyCode",outputColumnName:@"InsurancePolicyCode"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"InsurancePolicyName",outputColumnName:@"InsurancePolicyName"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Gender",@"MaritalStatus",@"IsSingle",@"IsDependentSpouse",@"IsFreelancer",@"CustomerId",@"ChildrenNumbers",@"DependentChildrenNumber",@"BirthMonth",@"YearBirth",@"ProfessionType",@"IncomeClassType",@"IncomeType",@"Country",@"Region",@"InsurancePolicyCode",@"InsurancePolicyName"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"InsurancePolicyId",inputColumnName:@"InsurancePolicyId"))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy(new LbfgsMaximumEntropyMulticlassTrainer.Options(){L1Regularization=0.08824962F,L2Regularization=0.0504961F,LabelColumnName=@"InsurancePolicyId",FeatureColumnName=@"Features"}))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
