// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MachineLearningModel
{
    public partial class MLClassifierCustomerFeature
    {
        /// <summary>
        /// model input class for MLClassifierCustomerFeature.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"CustomerId")]
            public float CustomerId { get; set; }

            [ColumnName(@"Gender")]
            public string Gender { get; set; }

            [ColumnName(@"BirthMonth")]
            public string BirthMonth { get; set; }

            [ColumnName(@"YearBirth")]
            public string YearBirth { get; set; }

            [ColumnName(@"MaritalStatus")]
            public string MaritalStatus { get; set; }

            [ColumnName(@"IsSingle")]
            public bool IsSingle { get; set; }

            [ColumnName(@"IsDependentSpouse")]
            public bool IsDependentSpouse { get; set; }

            [ColumnName(@"ChildrenNumbers")]
            public float ChildrenNumbers { get; set; }

            [ColumnName(@"DependentChildrenNumber")]
            public float DependentChildrenNumber { get; set; }

            [ColumnName(@"ProfessionType")]
            public string ProfessionType { get; set; }

            [ColumnName(@"IsFreelancer")]
            public bool IsFreelancer { get; set; }

            [ColumnName(@"IncomeClassType")]
            public string IncomeClassType { get; set; }

            [ColumnName(@"IncomeType")]
            public string IncomeType { get; set; }

            [ColumnName(@"Country")]
            public string Country { get; set; }

            [ColumnName(@"Region")]
            public string Region { get; set; }

            [ColumnName(@"InsurancePolicyId")]
            public float InsurancePolicyId { get; set; }

            [ColumnName(@"InsurancePolicyCode")]
            public string InsurancePolicyCode { get; set; }

            [ColumnName(@"InsurancePolicyName")]
            public string InsurancePolicyName { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLClassifierCustomerFeature.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"CustomerId")]
            public float CustomerId { get; set; }

            [ColumnName(@"Gender")]
            public float[] Gender { get; set; }

            [ColumnName(@"BirthMonth")]
            public float[] BirthMonth { get; set; }

            [ColumnName(@"YearBirth")]
            public float[] YearBirth { get; set; }

            [ColumnName(@"MaritalStatus")]
            public float[] MaritalStatus { get; set; }

            [ColumnName(@"IsSingle")]
            public float[] IsSingle { get; set; }

            [ColumnName(@"IsDependentSpouse")]
            public float[] IsDependentSpouse { get; set; }

            [ColumnName(@"ChildrenNumbers")]
            public float ChildrenNumbers { get; set; }

            [ColumnName(@"DependentChildrenNumber")]
            public float DependentChildrenNumber { get; set; }

            [ColumnName(@"ProfessionType")]
            public float[] ProfessionType { get; set; }

            [ColumnName(@"IsFreelancer")]
            public float[] IsFreelancer { get; set; }

            [ColumnName(@"IncomeClassType")]
            public float[] IncomeClassType { get; set; }

            [ColumnName(@"IncomeType")]
            public float[] IncomeType { get; set; }

            [ColumnName(@"Country")]
            public float[] Country { get; set; }

            [ColumnName(@"Region")]
            public float[] Region { get; set; }

            [ColumnName(@"InsurancePolicyId")]
            public uint InsurancePolicyId { get; set; }

            [ColumnName(@"InsurancePolicyCode")]
            public float[] InsurancePolicyCode { get; set; }

            [ColumnName(@"InsurancePolicyName")]
            public float[] InsurancePolicyName { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLClassifierCustomerFeature.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
